# @package _global_

# Defaults for training for the PushT dataset.

seed: 100000
skill: ???
dataset_repo_id: ${skill}
dataset_local_root_dir: "/home/ubuntu/efs/sfeng/lerobot/dataset/"

wandb:
  enable: true

hydra:
  run:
    dir: /home/ubuntu/efs/results/lerobot/outputs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}_${env.name}_${policy.name}_${hydra.job.name}
  job:
    name: ${skill}

override_dataset_stats:
  observation.images.wrist_right_minus:
    # stats from imagenet, since we use a pretrained vision model
    mean: [[[0.485]], [[0.456]], [[0.406]]]  # (c,1,1)
    std: [[[0.229]], [[0.224]], [[0.225]]]  # (c,1,1)
  observation.images.wrist_left_plus:
    # stats from imagenet, since we use a pretrained vision model
    mean: [[[0.485]], [[0.456]], [[0.406]]]  # (c,1,1)
    std: [[[0.229]], [[0.224]], [[0.225]]]  # (c,1,1)
  observation.images.scene_right_0:
    # stats from imagenet, since we use a pretrained vision model
    mean: [[[0.485]], [[0.456]], [[0.406]]]  # (c,1,1)
    std: [[[0.229]], [[0.224]], [[0.225]]]  # (c,1,1)
  observation.images.scene_left_0:
    # stats from imagenet, since we use a pretrained vision model
    mean: [[[0.485]], [[0.456]], [[0.406]]]  # (c,1,1)
    std: [[[0.229]], [[0.224]], [[0.225]]]  # (c,1,1)

training:
  offline_steps: 300000
  online_steps: 0
  eval_freq: 0
  save_freq: 10000
  log_freq: 250
  save_checkpoint: true
  num_workers: 8

  batch_size: 32

  grad_clip_norm: 10
  lr: 1.0e-4
  lr_scheduler: cosine
  lr_warmup_steps: 500
  adam_betas: [0.95, 0.999]
  adam_eps: 1.0e-8
  adam_weight_decay: 1.0e-6
  online_steps_between_rollouts: 1

  # VQ-BeT specific
  vqvae_lr: 1.0e-3
  n_vqvae_training_steps: 20000
  bet_weight_decay: 2e-4
  bet_learning_rate: 5.5e-5
  bet_betas: [0.9, 0.999]

  delta_timestamps:
    observation.images.wrist_right_minus: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    observation.images.wrist_left_plus: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    observation.images.scene_right_0: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    observation.images.scene_left_0: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    observation.state: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, 1)]"
    action: "[i / ${fps} for i in range(1 - ${policy.n_obs_steps}, ${policy.n_action_pred_token} + ${policy.action_chunk_size} - 1)]"

eval:
  n_episodes: 50
  batch_size: 50

policy:
  name: vqbet

  # Input / output structure.
  n_obs_steps: 2
  n_action_pred_token: 8
  action_chunk_size: 1

  input_shapes:
    # TODO(rcadene, alexander-soare): add variables for height and width from the dataset/env?
    observation.images.wrist_right_minus: [3, 480, 640]
    observation.images.wrist_left_plus: [3, 480, 640]
    observation.images.scene_right_0: [3, 480, 640]
    observation.images.scene_left_0: [3, 480, 640]
    observation.state: ["${env.state_dim}"]
  output_shapes:
    action: ["${env.action_dim}"]

  # Normalization / Unnormalization
  input_normalization_modes:
    observation.images.wrist_right_minus: mean_std
    observation.images.wrist_left_plus: mean_std
    observation.images.scene_right_0: mean_std
    observation.images.scene_left_0: mean_std
    observation.state: min_max
  output_normalization_modes:
    action: min_max

  # Architecture / modeling.
  # Vision backbone.
  vision_backbone: vit_b_16
  pretrained_backbone_weights: IMAGENET1K_SWAG_LINEAR_V1
  resize_shape: [256, 342]
  crop_shape: [224, 224]
  crop_is_random: True
  use_spatial_softmax: False
  use_group_norm: True
  spatial_softmax_num_keypoints: 32
  # VQ-VAE
  n_vqvae_training_steps: ${training.n_vqvae_training_steps}
  vqvae_n_embed: 16
  vqvae_embedding_dim: 256
  vqvae_enc_hidden_dim: 128
  # VQ-BeT
  gpt_block_size: 500
  gpt_input_dim: 512
  gpt_output_dim: 512
  gpt_n_layer: 8
  gpt_n_head: 8
  gpt_hidden_dim: 512
  dropout: 0.1
  mlp_hidden_dim: 1024
  offset_loss_weight: 10000.
  primary_code_loss_weight: 5.0
  secondary_code_loss_weight: 0.5
  bet_softmax_temperature: 0.1
  sequentially_select: False
